name: RhbHardcore
version: ${project.version}
main: com.rhbarber.hardcore.Hardcore
api-version: 1.21
authors: [Rhbarber]
description: SUFFERING!
website: https://rhbarber.com/

softdepend: [PlaceholderAPI]

commands:
  rhtest:
    description: Testing
  rhb:
    description: Main Command, "kills" argument made by NotEugenio_
  test:
    description: Me messing up with PlaceholderAPI just because